a = input('Digite algo:')
print(f'O tipo primitivo desse valor é ',type(a))
print('Só tem espaço? ', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Esta em minuscula?', a.islower())
print('Está capitalizada?', a.istitle())

